language: python
matrix:
  include:
    - python: 3.6.6
    - python: 3.7.0
      dist: xenial
      sudo: true
install:
  - pip install tox tox-travis coverage coveralls
script:
  - tox
  - coverage report
after_success:
  - coveralls